server:
  port: 8002
  address: 0.0.0.0

spring:
  main:
    web-application-type: reactive  # 网关必须是响应式
  application:
    name: zero-trust-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP

    loadbalancer:
      nacos:
        enabled: true  # 启用 Nacos 负载均衡支持
      ribbon:
        enabled: false  # 禁用 Ribbon

    gateway:
      discovery:
        locator:
          enabled: false  # 关闭自动发现路由
      routes:
        - id: zero-trust-identity
          uri: lb://zero-trust-identity
          predicates:
            - Path=/identity/**

        - id: zero-trust-policy
          uri: lb://zero-trust-policy
          predicates:
            - Path=/policy/**

        - id: zero-trust-monitoring
          uri: lb://zero-trust-monitoring
          predicates:
            - Path=/monitoring/**

        - id: zero-trust-trusteval
          uri: lb://zero-trust-trusteval
          predicates:
            - Path=/trusteval/**

        - id: zero-trust-collecting
          uri: lb://zero-trust-collecting
          predicates:
            - Path=/collecting/**





logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud.client.loadbalancer: TRACE
    reactor.loadbalancer: DEBUG
  reactor:
    ipc.netty: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
