server:
  port: 9014

spring:
  application:
    name: zero-trust-trusteval
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    url: jdbc:mysql://localhost:3306/ztrust_main?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1231234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.beans.factory.support: DEBUG
    feign: DEBUG